export CUDA_VISIBLE_DEVICES='5,6'
nohup python3 -m torch.distributed.launch --nproc_per_node=2 --master_port 29511 run_summarization.py \
--learning_rate 1e-4 \
--model_name_or_path 't5-base' \
--output_dir 'paperSummarization-QA-t5-1e4-16epoch-16bsz' \
--num_train_epochs 16 \
--per_device_train_batch_size 16 \
--per_device_eval_batch_size 16 \
--warmup_ratio 0.10 \
--fp16 false \
--eval_steps 100 \
--gradient_accumulation_steps 1 \
--evaluation_strategy 'steps' \
--logging_strategy 'steps' \
--save_strategy 'steps' \
--save_steps 100 \
--logging_steps 100 \
--train_file './filter_data/annotate/cleanTrainAnEvidenceOnly.json' \
--validation_file './filter_data/annotate/cleanDevAnEvidenceOnly.json' \
--test_file './filter_data/annotate/cleanTestAnEvidenceOnly.json' \
--max_source_length 512 \
--max_target_length 128 \
--pad_to_max_length false \
--source_prefix "Question Answering: " \
--do_train true \
--do_eval true \
--do_predict true \
--ddp_find_unused_parameters true \
--overwrite_output_dir true \
--prediction_loss_only false \
--load_best_model_at_end true \
--metric_for_best_model 'rougeL' \
--predict_with_generate true \
--greater_is_better true \
--num_beams 5  \
--save_total_limit 3 \
> paperSummarization-QA-t5-1e4-16epoch-16bsz.log 2>&1 &